service: push-notifications

provider:
  name: aws
  region: us-east-2
  stage: ${env:STAGE, 'dev'}
  runtime: python3.8
  environment:
    PYTHONPATH: "src:libs"
    STAGE: ${env:STAGE, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::GetAtt: [ NotificationTokensTable, Arn ]

package:
  exclude:
    - .cache/**
    - tests/**
    - test-env/**
  include:
    - ../../libs/goatcommons/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    cacheLocation: '.cache/'
  customDomain:
    basePath: 'notification'
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    createRoute53Record: false

functions:
  registerToken:
    handler: src/handlers.register_token_handler
    events:
      - http:
          path: register
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  sendNotification:
    handler: src/handlers.send_notification_handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ PushNotificationRequestQueue, Arn ]

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 10
        IdentitySource: method.request.header.Authorization
        Name: GoatCognitoAuthorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - 'Fn::ImportValue': ${self:provider.stage}-GoatfolioAppUserPoolArnOutput

    PushNotificationRequestQueue:
      Type: AWS::SQS::Queue
      Properties:
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "PushNotificationRequestDLQ"
              - "Arn"
          maxReceiveCount: 3
        QueueName: PushNotificationRequest
        VisibilityTimeout: 300

    PushNotificationRequestDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PushNotificationRequestDLQ

    NotificationTokensTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: "NotificationTokens"
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "subject"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "subject"
            KeyType: "HASH"

