Resources:
  PortfolioTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "Portfolio"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "subject"
          AttributeType: "S"
        - AttributeName: "ticker"
          AttributeType: "S"
        - AttributeName: "alias_ticker"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "subject"
          KeyType: "HASH"
        - AttributeName: "ticker"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: subjectAliasTickerGlobalIndex
          KeySchema:
            - AttributeName: "subject"
              KeyType: "HASH"
            - AttributeName: "alias_ticker"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
