Resources:
  PortfolioTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "Portfolio"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "subject"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "subject"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
