Resources:
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ElastiCache Security Group
      VpcId:
        Fn::ImportValue: serverless-goatfolio-${self:provider.stage}-VpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 10.50.64.0/19
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 10.50.96.0/19

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Cache Subnet Group
      SubnetIds:
        - Fn::ImportValue: serverless-goatfolio-${self:provider.stage}-PrivateSubnet1ID
        - Fn::ImportValue: serverless-goatfolio-${self:provider.stage}-PrivateSubnet2ID

  RedisElasticacheCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      Engine: redis
      CacheNodeType: cache.t2.micro
      NumCacheNodes: '1'
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt RedisSecurityGroup.GroupId