Resources:
  PortfolioAddOrUpdatedInvestmentSubscriber:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "PortfolioAddOrUpdatedInvestmentSubscriberDLQ"
            - "Arn"
        maxReceiveCount: 5
      FifoQueue: true
      QueueName: PortfolioAddOrUpdatedInvestmentSubscriber.fifo
      VisibilityTimeout: 300

  PortfolioAddOrUpdatedInvestmentSubscriberDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PortfolioAddOrUpdatedInvestmentSubscriberDLQ.fifo
      FifoQueue: true

#  Subscription:
#    Type: 'AWS::SNS::Subscription'
#    Properties:
#      TopicArn:
#        'Fn::ImportValue': ${self:provider.stage}-AddedOrUpdatedInvestmentTopic
#      Endpoint: !GetAtt PortfolioAddOrUpdatedInvestmentSubscriber.Arn
#      Protocol: sqs
#      RawMessageDelivery: 'true'
