pipeline {
    agent {
        docker {
            image 'victorclc/node-serverless'
            args '-u 127:998 -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    environment {
        HOME="."
        SERVICE_PATH="${env.WORKSPACE}/services/vandelay-api"
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id-dev')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key-dev')
        MARKET_STACK_API_KEY="${env.MARKET_STACK_API_KEY}"
        DOMAIN_NAME='dev.victorclc.com.br'
        SLS_DEBUG='*'
    }
    stages {
        stage('Clone') {
            steps {
                git(
                    url: 'git@github.com:victorclc/goatfolio-serverless.git',
                    credentialsId: 'github-ssh',
                    branch: 'master'
                )
             }
        }
        stage('Tests') {
            steps {
                dir('services/vandelay-api') {
                    //sh 'TODO tests'
                }
            }
        }
        stage('Sonar') {
            steps {
                dir('services/vandelay-api'){
                    sh 'sonar-scanner \
                        -Dsonar.projectKey=vandelay-api \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://192.168.0.100:9000 \
                        -Dsonar.login=f996adea9c2953fe29570838e12969477c133aab'
                }
             }
        }
        stage('Common Resources Deploy') {
            steps {
                sh 'serverless deploy'
             }
        }
        stage('Service Deploy') {
            steps {
                 dir('services/vandelay-api'){
                    sh 'npm install'
                    sh 'serverless deploy'
                }
            }
        }
    }
}