service: serverless-goatfolio

provider:
  name: aws
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  sesArn: ${env:SES_ARN}
  sesFrom: ${env:SES_FROM}

resources:
  Parameters:
    AvailabilityZone1:
      Description: The first availability zone in the region
      Type: AWS::EC2::AvailabilityZone::Name
      ConstraintDescription: Must be a valid availability zone
      Default: sa-east-1a

    AvailabilityZone2:
      Description: The second availability zone in the region
      Type: AWS::EC2::AvailabilityZone::Name
      ConstraintDescription: Must be a valid availability zone
      Default: sa-east-1b

  Metadata:
    AWS::CloudFormation::Interface:
      ParameterGroups:
        - Label:
            default: Region Availability Zones
          Parameters:
            - AvailabilityZone1
            - AvailabilityZone2
        - Label:
            default: Ingress Ports
          Parameters:
            - ELBIngressPort
            - AppIngressPort
      ParameterLabels:
        AvailabilityZone1:
          default: Availability Zone 1
        AvailabilityZone2:
          default: Availability Zone 2

  Mappings:
    # Maps CIDR blocks to VPC and various subnets
    CIDRMap:
      VPC:
        CIDR: 10.50.0.0/16
      Public1:
        CIDR: 10.50.0.0/24
      Public2:
        CIDR: 10.50.1.0/24
      Private1:
        CIDR: 10.50.64.0/19
      Private2:
        CIDR: 10.50.96.0/19

  - ${file(resources/network-cf-resources.yml)}

  # APP RESOURCES AND STUFF
  - Resources:
    GoatfolioAppUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        EmailVerificationSubject: "GOATFOLIO - Código de verificação"
        EmailVerificationMessage: "O código de verificação é {####}"
        EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          From: ${self:provider.sesFrom}
          SourceArn: ${self:provider.sesArn}
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            RequireUppercase: true
            TemporaryPasswordValidityDays: 1
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        Schema:
          - Name: given_name
            Required: true
            Mutable: true
        UsernameConfiguration:
          CaseSensitive: false
        UserPoolName: GoatfolioPool

    MobilePoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: 'mobile-pool'
        TokenValidityUnits:
          AccessToken: minutes
          IdToken: minutes
          RefreshToken: days
        RefreshTokenValidity: 3650
        AccessTokenValidity: 60
        IdTokenValidity: 60
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_CUSTOM_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        PreventUserExistenceErrors: ENABLED
        EnableTokenRevocation: false
        UserPoolId:
          Ref: GoatfolioAppUserPool

    InvestmentsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Investments
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "subject"
            AttributeType: "S"
          - AttributeName: "date"
            AttributeType: "N"
          - AttributeName: "ticker"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "subject"
            KeyType: "HASH"
          - AttributeName: "id"
            KeyType: "RANGE"
        GlobalSecondaryIndexes:
          - IndexName: subjectDateGlobalIndex
            KeySchema:
              - AttributeName: "subject"
                KeyType: "HASH"
              - AttributeName: "date"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL
          - IndexName: tickerSubjectGlobalIndex
            KeySchema:
              - AttributeName: "ticker"
                KeyType: "HASH"
              - AttributeName: "subject"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL

    CeiImportRequestQueue:
      Type: AWS::SQS::Queue
      Properties:
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "CeiImportRequestDLQ"
              - "Arn"
          maxReceiveCount: 5
        QueueName: CeiImportRequest
        VisibilityTimeout: 900

    CeiImportRequestDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CeiImportRequestDLQ

    CeiImportResultQueue:
      Type: AWS::SQS::Queue
      Properties:
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "CeiImportResultDLQ"
              - "Arn"
          maxReceiveCount: 5
        QueueName: CeiImportResult
        VisibilityTimeout: 300

    CeiImportResultDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CeiImportResultDLQ

    NotificationMessagesConfigTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: NotificationMessagesConfig
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "message_key"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "message_key"
            KeyType: "HASH"

    EventsToNotifyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: EventsToNotify
        VisibilityTimeout: 300

    PushNotificationRequestQueue:
      Type: AWS::SQS::Queue
      Properties:
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "PushNotificationRequestDLQ"
              - "Arn"
          maxReceiveCount: 3
        QueueName: PushNotificationRequest
        VisibilityTimeout: 300

    PushNotificationRequestDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: PushNotificationRequestDLQ

    MarketDataTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: "MarketData"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "ticker"
            AttributeType: "S"
          - AttributeName: "candle_date"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "ticker"
            KeyType: "HASH"
          - AttributeName: "candle_date"
            KeyType: "RANGE"

    PortfolioTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: "Portfolio"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "subject"
            AttributeType: "S"
          - AttributeName: "ticker"
            AttributeType: "S"
          - AttributeName: "alias_ticker"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "subject"
            KeyType: "HASH"
          - AttributeName: "ticker"
            KeyType: "RANGE"
        GlobalSecondaryIndexes:
          - IndexName: subjectAliasTickerGlobalIndex
            KeySchema:
              - AttributeName: "subject"
                KeyType: "HASH"
              - AttributeName: "alias_ticker"
                KeyType: "RANGE"
            Projection:
              ProjectionType: ALL

  - Outputs:
    Name:
      Description: VPC Stack Name
      Value: !Ref AWS::StackName
      Export:
        Name: !Sub ${AWS::StackName}-Name
    VPCId:
      Description: VPC ID
      Value: !Ref VPC
      Export:
        Name: !Sub "${AWS::StackName}-VpcID"
    VpcCidr:
      Description: Vpc cidr block
      Value: !FindInMap [ CIDRMap, VPC, CIDR ]
      Export:
        Name: !Sub "${AWS::StackName}-vpc-cidr"
    PublicSubnet1:
      Description: Public subnet 1 ID
      Value: !Ref PublicSubnet1
      Export:
        Name: !Sub "${AWS::StackName}-PublicSubnet1ID"
    PublicSubnet2:
      Description: Public subnet 2 ID
      Value: !Ref PublicSubnet2
      Export:
        Name: !Sub "${AWS::StackName}-PublicSubnet2ID"
    PrivateSubnet1:
      Description: Private subnet 1 ID
      Value: !Ref PrivateSubnet1
      Export:
        Name: !Sub "${AWS::StackName}-PrivateSubnet1ID"
    PrivateSubnet2:
      Description: Private subnet 2 ID
      Value: !Ref PrivateSubnet2
      Export:
        Name: !Sub "${AWS::StackName}-PrivateSubnet2ID"

    GoatfolioAppUserPoolArnOutput:
      Value:
        Fn::GetAtt: [ GoatfolioAppUserPool, Arn ]
      Export:
        Name: ${self:provider.stage}-GoatfolioAppUserPoolArnOutput
    InvestmentsTableArnOutput:
      Value:
        Fn::GetAtt: [ InvestmentsTable, Arn ]
      Export:
        Name: ${self:provider.stage}-InvestmentsTableArnOutput
    CeiImportRequestQueueArn:
      Value:
        Fn::GetAtt: [ CeiImportRequestQueue, Arn ]
      Export:
        Name: ${self:provider.stage}-CeiImportRequestQueueArn
    CeiImportResultQueueArn:
      Value:
        Fn::GetAtt: [ CeiImportResultQueue, Arn ]
      Export:
        Name: ${self:provider.stage}-CeiImportResultQueueArn
    InvestmentTableStreamArn:
      Value:
        Fn::GetAtt: [ InvestmentsTable, StreamArn ]
      Export:
        Name: ${self:provider.stage}-InvestmentTableStreamArn
    NotificationMessagesConfigTableArnOutput:
      Value:
        Fn::GetAtt: [ NotificationMessagesConfigTable, Arn ]
      Export:
        Name: ${self:provider.stage}-NotificationMessagesConfigTableArnOutput
    EventsToNotifyQueueArn:
      Value:
        Fn::GetAtt: [ EventsToNotifyQueue, Arn ]
      Export:
        Name: ${self:provider.stage}-EventsToNotifyQueueArn
    PushNotificationRequestArnOutput:
      Value:
        Fn::GetAtt: [ PushNotificationRequestQueue, Arn ]
      Export:
        Name: ${self:provider.stage}-PushNotificationRequestArnOutput
    MarketDataTableArnOutput:
      Value:
        Fn::GetAtt: [ MarketDataTable, Arn ]
      Export:
        Name: ${self:provider.stage}-MarketDataTableArnOutput
    PortfolioTableArnOutput:
      Value:
        Fn::GetAtt: [ PortfolioTable, Arn ]
      Export:
        Name: ${self:provider.stage}-PortfolioTableArnOutput