Resources:
  ImportsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "Imports"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "subject"
          AttributeType: "S"
        - AttributeName: "datetime"
          AttributeType: "N"
        - AttributeName: "status"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "subject"
          KeyType: "HASH"
        - AttributeName: "datetime"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - IndexName: subjectStatusLocalIndex
          KeySchema:
            - AttributeName: "subject"
              KeyType: "HASH"
            - AttributeName: "status"
              KeyType: "RANGE"
          Projection:
            ProjectionType: KEYS_ONLY
