Resources:
  CeiImportResultQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "CeiImportResultDLQ"
            - "Arn"
        maxReceiveCount: 5
      QueueName: CeiImportResult
      VisibilityTimeout: 300

  CeiImportResultDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CeiImportResultDLQ

Outputs:
  CeiImportResultQueueArn:
    Value:
      Fn::GetAtt: [ CeiImportResultQueue, Arn ]
    Export:
      Name: ${self:provider.stage}-CeiImportResultQueueArn