service: push-notifications

provider:
  name: aws
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  runtime: python3.8
  memorySize: 512
  environment:
    PYTHONPATH: "src:shared/libs"
    STAGE: ${env:STAGE, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - Fn::GetAtt: [ NotificationTokensTable, Arn ]
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:DescribeParameters
      Resource: arn:aws:ssm:${self:provider.region}:*:parameter/firebase-credentials

package:
  exclude:
    - .cache/**
    - tests/**
    - test-env/**
    - node_modules/**
  include:
    - ../shared/libs/goatcommons/**

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3.8
    cacheLocation: '.cache/'
  customDomain:
    basePath: 'notification'
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'

functions:
  registerToken:
    handler: src/handlers.register_token_handler
    events:
      - http:
          path: register
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  unregisterToken:
    handler: src/handlers.unregister_token_handler
    events:
      - http:
          path: unregister
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  sendNotification:
    handler: src/handlers.send_notification_handler
    events:
      - sqs:
          arn:
            'Fn::ImportValue': ${self:provider.stage}-PushNotificationRequestArnOutput

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 10
        IdentitySource: method.request.header.Authorization
        Name: GoatCognitoAuthorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - 'Fn::ImportValue': ${self:provider.stage}-GoatfolioAppUserPoolArnOutput

    NotificationTokensTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: "NotificationTokens"
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "subject"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "subject"
            KeyType: "HASH"

