class OperationType:
    BUY = "BUY"
    SELL = "SELL"


class InvestmentsType:
    STOCK = "STOCK"
    US_STOCK = "US_STOCK"
    FIXED_INCOME = "FIXED_INCOME"
    PRE_FIXED = "PRE_FIXED"
    POST_FIXED = "POST_FIXED"
    CHECKING_ACCOUNT = "CHECKING_ACCOUNT"
    CRYPTO = "CRYPTO"


class StockSubType:
    STOCK = "STOCK"
    REAL_STATE = "REAL_STATE"
    BRAZILIAN_DEPOSIT_RECEIPT = "BRAZILIAN_DEPOSIT_RECEIPT"
    EXCHANGE_TRADED_FUND = "EXCHANGE_TRADED_FUND"
