service: performance-api

provider:
  name: aws
  timeout: 300
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  runtime: python3.8
  environment:
    PYTHONPATH: "src:libs"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        'Fn::ImportValue': ${self:provider.stage}-InvestmentsTableArnOutput
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt: [ PortfolioTable, Arn ]
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
      Resource:
        'Fn::ImportValue': ${self:provider.stage}-MarketDataTableArnOutput
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        'Fn::ImportValue': ${self:provider.stage}-EventsToNotifyQueueArn


package:
  exclude:
    - .cache/**
    - tests/**
  include:
    - ../../libs/goatcommons/**

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    basePath: 'performance'
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    createRoute53Record: false

functions:
  consolidatePortfolio:
    handler: src/handlers.consolidate_portfolio_handler
    events:
      - stream:
          type: dynamodb
          arn:
            'Fn::ImportValue': ${self:provider.stage}-InvestmentTableStreamArn

  performanceSummary:
    handler: src/handlers.performance_summary_handler
    events:
      - http:
          path: summary
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  performanceRentability:
    handler: src/handlers.performance_rentability_handler
    events:
      - http:
          path: rentability
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer


  performancePortfolio:
    handler: src/handlers.performance_portfolio_handler
    events:
      - http:
          path: portfolio
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer


  performancePortfolioTicker:
    handler: src/handlers.performance_portfolio_ticker_handler
    events:
      - http:
          path: portfolio/{ticker}
          request:
            parameters:
              paths:
                ticker: true
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 10
        IdentitySource: method.request.header.Authorization
        Name: GoatCognitoAuthorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - 'Fn::ImportValue': ${self:provider.stage}-GoatfolioAppUserPoolArnOutput

    PortfolioTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: "Portfolio"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "subject"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "subject"
            KeyType: "HASH"

#    RedisElasticacheCluster:
#      Type: 'AWS::ElastiCache::CacheCluster'
#      Properties:
#        Engine: redis
#        CacheNodeType: cache.t2.micro
#        NumCacheNodes: '1'
