service: vandelay-api

provider:
  name: aws
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  runtime: python3.8
  environment:
    PYTHONPATH: "src:shared/libs"
    BASE_API_URL: ${env:DOMAIN_NAME}
    API_KEY_SECRET_NAME: ${env:API_KEY_SECRET_NAME}
  iamRoleStatements: ${file(resources/roles-cf-statements.yml)}

package:
  exclude:
    - .cache/**
    - tests/**
    - test-env/**
    - node_modules/**
    - resources/**
  include:
    - ../shared/libs/goatcommons/**
    - ../shared/libs/brutils/**
    - ../shared/libs/investments/**

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3.8
    cacheLocation: '.cache/'
  customDomain:
    basePath: vandelay
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'

functions:
  ceiImportRequest:
    handler: src/handlers.cei_import_request_handler
    events:
      - http:
          path: cei
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  ceiImportResult:
    handler: src/handlers.cei_import_result_handler
    events:
      - sqs:
          arn:
            'Fn::ImportValue': ${self:provider.stage}-CeiImportResultQueueArn

  getCEIInfo:
    handler: src/handlers.cei_info_request_handler
    events:
      - http:
          path: cei/info
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  getImportStatus:
    handler: src/handlers.import_status_handler
    events:
      - http:
          path: cei
          parameters:
            querystrings:
              datetime: true
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

resources:
  Resources:
    ImportsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: "Imports"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "subject"
            AttributeType: "S"
          - AttributeName: "datetime"
            AttributeType: "N"
          - AttributeName: "status"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "subject"
            KeyType: "HASH"
          - AttributeName: "datetime"
            KeyType: "RANGE"
        LocalSecondaryIndexes:
          - IndexName: subjectStatusLocalIndex
            KeySchema:
              - AttributeName: "subject"
                KeyType: "HASH"
              - AttributeName: "status"
                KeyType: "RANGE"
            Projection:
              ProjectionType: KEYS_ONLY

    CEIInfoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: "CEIInfo"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "subject"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "subject"
            KeyType: "HASH"
