service: event-notifier

provider:
  name: aws
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  timeout: 300
  runtime: python3.8
  environment:
    PYTHONPATH: "src:libs"
    WEBHOOK_URL: ${env:WEBHOOK_URL, 'https://discord.com/api/webhooks/836095821765541909/61ZRaWHqunwfwmxlggGlv1ytEQXTJ2P6Jo-G8u8FvFREMphxS3zF7b_ypbU-CP-AcRKv'}

package:
  exclude:
    - .cache/**
    - tests/**
    - node_modules/**
  include:
    - ../../libs/goatcommons/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3
    cacheLocation: '.cache/'

functions:
  shitNotifierHandler:
    handler: src/handlers.shit_notify_handler
    events:
      - sqs:
          arn:
            'Fn::ImportValue': ${self:provider.stage}-EventsToNotifyQueueArn
