service: event-notifier

provider:
  name: aws
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  timeout: 300
  runtime: python3.8
  environment:
    PYTHONPATH: "src:libs"
    DEV_WEBHOOK_URL: ${env:DEV_WEBHOOK_URL, 'https://discord.com/api/webhooks/836095821765541909/61ZRaWHqunwfwmxlggGlv1ytEQXTJ2P6Jo-G8u8FvFREMphxS3zF7b_ypbU-CP-AcRKv'}
    PROD_WEBHOOK_URL: ${env:PROD_WEBHOOK_URL, 'https://discord.com/api/webhooks/880771481007693825/yS5pVrrYvpGtmN2XqtcEf4t9Cio5PxIIuB9AHMlXv8Xq7q2RjFuaBTppWvrOJRp_Llh0'}
    STAGE: ${self:provider.stage}

package:
  exclude:
    - .cache/**
    - tests/**
    - node_modules/**
  include:
    - ../../libs/goatcommons/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3.8
    cacheLocation: '.cache/'

functions:
  shitNotifierHandler:
    handler: src/handlers.shit_notify_handler
    events:
      - sqs:
          arn:
            'Fn::ImportValue': ${self:provider.stage}-EventsToNotifyQueueArn
