service: event-notifier

provider:
  name: aws
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  timeout: 300
  runtime: python3.8
  memorySize: 256
  environment:
    PYTHONPATH: "src:shared/libs"
    DEFAULT_WEBHOOK_URL: ${env:DEFAULT_WEBHOOK_URL, 'https://discord.com/api/webhooks/836095821765541909/61ZRaWHqunwfwmxlggGlv1ytEQXTJ2P6Jo-G8u8FvFREMphxS3zF7b_ypbU-CP-AcRKv'}
    COGNITO_WEBHOOK_URL: ${env:COGNITO_WEBHOOK_URL, 'https://discord.com/api/webhooks/965932774068461608/3Boxrq6-tAbRT04UDYyXnniBAxEMvYHKU0EfT8aL88xp-mbRlEpDziV0avmbVCe9T7Yq'}

package:
  exclude:
    - .cache/**
    - tests/**
    - node_modules/**
    - resources/**
  include:
    - ../shared/libs/goatcommons/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3.8
    cacheLocation: '.cache/'

functions:
  shitNotifierHandler:
    handler: src/handlers.shit_notify_handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ EventsToNotifyQueue, Arn ]

resources:
  - ${file(resources/queue-cf-resources.yml)}
