from enum import Enum


class EventType(Enum):
    SPLIT = "DESDOBRAMENTO"
    GROUP = "GRUPAMENTO"
    INCORPORATION = "INCORPORACAO"
    BONIFICACAO = "BONIFICACAO"
    REST_CAP_ACOES = "REST CAP ACOES"
    CIS_RED_CAP = "CIS RED CAP"
    RESG_TOTAL_RV = "RESG TOTAL RV"
