Resources:
  CorporateEventsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "CorporateEvents"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "isin_code"
          AttributeType: "S"
        - AttributeName: "with_date"
          AttributeType: "S"
        - AttributeName: "type"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "type"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - IndexName: typeDateLocalIndex
          KeySchema:
            - AttributeName: "type"
              KeyType: "HASH"
            - AttributeName: "with_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: isinDateGlobalIndex
          KeySchema:
            - AttributeName: "isin_code"
              KeyType: "HASH"
            - AttributeName: "with_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
  ManualCorporateEventsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "ManualCorporateEvents"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "subject"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "with_date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "subject"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
