Resources:
  FaqTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "Faq"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "topic"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "topic"
          KeyType: "HASH"
