service: cei-crawler

provider:
  name: aws
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  timeout: 300
  runtime: python3.8
  environment:
    PYTHONPATH: "src:libs"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        'Fn::ImportValue': ${self:provider.stage}-CeiImportResultQueueArn
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
      Resource: arn:aws:s3:::${self:provider.stage}-prod-headlesschromium/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        'Fn::ImportValue': ${self:provider.stage}-EventsToNotifyQueueArn


package:
  exclude:
    - .cache/**
    - tests/**
  include:
    - ../../libs/goatcommons/**
    - ../../libs/lessmium/**

functions:
  ceiExtractHandler:
    handler: src/handlers.cei_extract_handler
    reservedConcurrency: 10
    events:
      - sqs:
          arn:
            'Fn::ImportValue': ${self:provider.stage}-CeiImportRequestQueueArn
