service: cotahist-transformer

provider:
  name: aws
  memorySize: 2048
  region: us-east-2
  stage: ${env:STAGE, 'dev'}
  runtime: python3.8
  timeout: 300
  environment:
    PYTHONPATH: "src:libs"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-east-2:831967415635:secret:rds-db-credentials/cluster-B7EKYQNIWMBMYI6I6DNK6ICBEE/postgres-z9xJqf"
    - Effect: Allow
      Action:
        - rds-data:BatchExecuteStatement
      Resource: "arn:aws:rds:us-east-2:831967415635:cluster:serverless-goatfolio-dev-marketdatardscluster-dq6ryzdhjru0"
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::${self:provider.stage}-b3cotahist/*


package:
  exclude:
    - .cache/**
    - tests/**
    - test-env/**
  include:
    - ../../libs/auroradata/**
    - ../../libs/goatcommons/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    cacheLocation: '.cache/'

functions:
  transformCotaHist:
    handler: handlers.transform_cota_hist_handler
    vpc:
      securityGroupIds:
        - sg-15f9666f
      subnetIds:
        - subnet-0525b98aa3176a425
        - subnet-0f2a8d4b2c04a5b6a
    events:
      - s3:
          bucket: ${self:provider.stage}-b3cotahist
          event: s3:ObjectCreated:Put
          rules:
            - prefix: monthly/
            - suffix: .TXT
      - s3:
          bucket: ${self:provider.stage}-b3cotahist
          event: s3:ObjectCreated:CompleteMultipartUpload
          rules:
            - prefix: monthly/
            - suffix: .TXT

resources:
  Resources:
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Creating policy for vpc connetion.
        Roles:
          - { "Ref": "IamRoleLambdaExecution" }
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: "*"