Resources:
  DividendsAPIAddOrUpdatedInvestmentSubscriber:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "DividendsAPIAddOrUpdatedInvestmentSubscriberDLQ"
            - "Arn"
        maxReceiveCount: 5
      FifoQueue: true
      QueueName: DividendsAPIAddOrUpdatedInvestmentSubscriber.fifo
      VisibilityTimeout: 300
  DividendsAPIAddOrUpdatedInvestmentSubscriberDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DividendsAPIAddOrUpdatedInvestmentSubscriberDLQ.fifo
      FifoQueue: true

  Subscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn:
        'Fn::ImportValue': ${self:provider.stage}-AddedOrUpdatedInvestmentTopic
      Endpoint: !GetAtt DividendsAPIAddOrUpdatedInvestmentSubscriber.Arn
      Protocol: sqs
      RawMessageDelivery: 'true'
  SNS2QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DividendsAPIAddOrUpdatedInvestmentSubscriber
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt DividendsAPIAddOrUpdatedInvestmentSubscriber.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn":
                  'Fn::ImportValue': ${self:provider.stage}-AddedOrUpdatedInvestmentTopic