Resources:
  NotificationTokensTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "NotificationTokens"
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "subject"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "subject"
          KeyType: "HASH"

  NotificationMessagesConfigTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: NotificationMessagesConfig
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "message_key"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "message_key"
          KeyType: "HASH"
