service: portfolio-api

provider:
  name: aws
  region: us-east-2
  stage: ${env:STAGE, 'dev'}
  runtime: python3.8
  environment:
    PYTHONPATH: "src:libs"

package:
  exclude:
    - .cache/**
    - tests/**
  include:
    - ../../libs/goatcommons/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    cacheLocation: '.cache/'

functions:
  postInvestment:
    handler: src/handlers.post_investment_handler
    events:
      - http:
          path: investments/
          method: post
