service: portfolio-api

provider:
  name: aws
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  runtime: python3.8
  environment:
    PYTHONPATH: "src:libs"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - 'Fn::ImportValue': ${self:provider.stage}-InvestmentsTableArnOutput
        - Fn::Join:
            - ''
            - - 'Fn::ImportValue': ${self:provider.stage}-InvestmentsTableArnOutput
              - '/index/*'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - 'Fn::ImportValue': ${self:provider.stage}-PortfolioTableArnOutput
        - Fn::Join:
            - ''
            - - 'Fn::ImportValue': ${self:provider.stage}-PortfolioTableArnOutput
              - '/index/*'
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        'Fn::ImportValue': ${self:provider.stage}-EventsToNotifyQueueArn


  apiGateway:
    apiKeys:
      - portfolio-api-key

package:
  exclude:
    - .cache/**
    - tests/**
    - node_modules/**
  include:
    - ../../libs/goatcommons/**

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3.8
    cacheLocation: '.cache/'
  customDomain:
    basePath: portfolio
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'

functions:
  getInvestments:
    handler: src/handlers.get_investments_handler
    events:
      - http:
          path: investments/
          method: get
          request:
            parameters:
              querystrings:
                date: false
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  addInvestment:
    handler: src/handlers.add_investment_handler
    events:
      - http:
          path: investments/
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  editInvestment:
    handler: src/handlers.edit_investment_handler
    events:
      - http:
          path: investments/
          method: put
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  deleteInvestments:
    handler: src/handlers.delete_investment_handler
    events:
      - http:
          path: investments/{investmentid}
          request:
            parameters:
              paths:
                investmentid: true
          method: delete
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  batchAddInvestments:
    handler: src/handlers.batch_add_investments_handler
    events:
      - http:
          path: investments/batch
          method: post
          private: true

  asyncAddInvestment:
    handler: src/handlers.async_add_investment_handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ AddInvestmentQueue, Arn ]

  consolidatePortfolio:
    handler: src/handlers.consolidate_portfolio_handler
    events:
      - stream:
          type: dynamodb
          arn:
            'Fn::ImportValue': ${self:provider.stage}-InvestmentTableStreamArn

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 10
        IdentitySource: method.request.header.Authorization
        Name: GoatCognitoAuthorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - 'Fn::ImportValue': ${self:provider.stage}-GoatfolioAppUserPoolArnOutput

    AddInvestmentQueue:
      Type: AWS::SQS::Queue
      Properties:
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "AddInvestmentQueueDLQ"
              - "Arn"
          maxReceiveCount: 5
        QueueName: AddInvestmentQueue
        VisibilityTimeout: 300

    AddInvestmentQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: AddInvestmentQueueDLQ

  Outputs:
    AddInvestmentQueueArn:
      Value:
        Fn::GetAtt: [ AddInvestmentQueue, Arn ]
      Export:
        Name: ${self:provider.stage}-AddInvestmentQueueArn
