Resources:
  TickerInfoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "TickerInfo"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ticker"
          AttributeType: "S"
        - AttributeName: "isin"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ticker"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: isinGlobalIndex
          KeySchema:
            - AttributeName: "isin"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
  MarketDataTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: "MarketData"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ticker"
          AttributeType: "S"
        - AttributeName: "candle_date"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ticker"
          KeyType: "HASH"
        - AttributeName: "candle_date"
          KeyType: "RANGE"
Outputs:
  TickerInfoTableArnOutput:
    Value:
      Fn::GetAtt: [ TickerInfoTable, Arn ]
    Export:
      Name: ${self:provider.stage}-TickerInfoTableArnOutput
  MarketDataTableArnOutput:
    Value:
      Fn::GetAtt: [ MarketDataTable, Arn ]
    Export:
      Name: ${self:provider.stage}-MarketDataTableArnOutput