service: backoffice-api

provider:
  name: aws
  memorySize: 512
  region: sa-east-1
  stage: ${env:STAGE, 'dev'}
  runtime: python3.8
  timeout: 30
  environment:
    LOG_LEVEL: DEBUG
    PYTHONPATH: "src:shared/libs"
  iamRoleStatements: ${file(resources/roles-cf-statements.yml)}
  endpointType: regional
  tracing:
    lambda: true

package:
  exclude:
    - .cache/**
    - tests/**
    - test-env/**
    - node_modules/**
    - resources/**
  include:
    - ../shared/libs/goatcommons/**

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3.8
    cacheLocation: '.cache/'
  customDomain:
    basePath: backoffice
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'

functions:
  postConfirmationTrigger:
    handler: src/adapters/inbound/cognito_triggers.post_confirmation_trigger

resources:
#  - ${file(resources/authorizer-cf-resources.yml)}
  - ${file(resources/functions-cf-outputs.yml)}
