Resources:
  CeiImportResultQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "CeiImportResultDLQ"
            - "Arn"
        maxReceiveCount: 5
      QueueName: CeiImportResult
      VisibilityTimeout: 300

  CeiImportResultDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CeiImportResultDLQ

  CeiImportRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "CeiImportRequestDLQ"
            - "Arn"
        maxReceiveCount: 5
      QueueName: CeiImportRequest
      VisibilityTimeout: 300

  CeiImportRequestDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CeiImportRequestDLQ

Outputs:
  CeiImportResultQueueArn:
    Value:
      Fn::GetAtt: [ CeiImportResultQueue, Arn ]
    Export:
      Name: ${self:provider.stage}-CeiImportResultQueueArn

  CeiImportRequestQueueArn:
    Value:
      Fn::GetAtt: [ CeiImportRequestQueue, Arn ]
    Export:
      Name: ${self:provider.stage}-CeiImportRequestQueueArn

  CeiImportRequestDLQQueueArn:
    Value:
      Fn::GetAtt: [ CeiImportRequestDLQ, Arn ]
    Export:
      Name: ${self:provider.stage}-CeiImportRequestDLQQueueArn