name: cei-crawler

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'backend/services/cei-crawler/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SERVICE_PATH: ./backend/services/cei-crawler

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.SERVICE_PATH}}
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo $GITHUB_REF
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "STAGE=prod" >> "$GITHUB_ENV"
            echo "DOMAIN_NAME=api.goatfolio.com.br" >> "$GITHUB_ENV"
            echo "AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}" >> "$GITHUB_ENV"
            echo "AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}" >> "$GITHUB_ENV"
          else
            echo "STAGE=dev" >> "$GITHUB_ENV"
            echo "DOMAIN_NAME=dev.goatfolio.com.br" >> "$GITHUB_ENV"
            echo "AWS_ACCESS_KEY_ID=${{secrets.DEV_AWS_ACCESS_KEY_ID}}" >> "$GITHUB_ENV"
            echo "AWS_SECRET_ACCESS_KEY=${{secrets.DEV_AWS_SECRET_ACCESS_KEY}}" >> "$GITHUB_ENV"
          fi
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setting up environment variables
        run: echo PYTHONPATH="../../libs:src:tests" >> $GITHUB_ENV
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          if [ -d tests/ ]; then pytest tests/; fi
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing NPM dependencies
        run: npm ci
      - name: Deploy
        run: npx serverless deploy
      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}