name: DEV goatfolio-serverless

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  STAGE: dev
  DOMAIN_NAME: 'api.goatfolio.com.br'
  SES_ARN: 'arn:aws:ses:sa-east-1:138414734174:identity/noreply+dev@goatfolio.com.br'
  SES_FROM: 'noreply+dev@goatfolio.com.br'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing NPM dependencies
        run: npm ci
      - name: Deploy
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
