name: Tests and Lint validation

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches: [ master, develop ]

env:
  STAGE: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
    run:
      working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install flake8 and pytest
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Setting up environment variables
        run: echo PYTHONPATH="../../libs:src:tests" >> $GITHUB_ENV
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          for service in $(ls services/); do cd services/$service; if [ -d tests/ ]; then echo "Testing $service"; pip install -r requirements.txt; pytest tests/; fi; cd -; done
      - name: Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}